# Generated by Django 6.1.1 on 2026-09-27 04:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import apps.profiles.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("career", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False, editable=False)),
                ("published_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_title_en", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_title_ko", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_title_uz", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("seo_description_en", models.CharField(blank=True, max_length=160, null=True)),
                ("seo_description_ko", models.CharField(blank=True, max_length=160, null=True)),
                ("seo_description_uz", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("home", "Home (/)"),
                            ("about", "About (/about/)"),
                            ("role", "Role (/<slug>/)"),
                        ],
                        default="role",
                        max_length=5,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Role profiles live at /<slug>/. Never translated.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80, null=True)),
                ("name_ko", models.CharField(max_length=80, null=True)),
                ("name_uz", models.CharField(max_length=80, null=True)),
                ("switcher_label", models.CharField(blank=True, max_length=40)),
                ("switcher_label_en", models.CharField(blank=True, max_length=40, null=True)),
                ("switcher_label_ko", models.CharField(blank=True, max_length=40, null=True)),
                ("switcher_label_uz", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "headline",
                    models.CharField(blank=True, help_text="Required to publish.", max_length=160),
                ),
                (
                    "headline_en",
                    models.CharField(
                        blank=True, help_text="Required to publish.", max_length=160, null=True
                    ),
                ),
                (
                    "headline_ko",
                    models.CharField(
                        blank=True, help_text="Required to publish.", max_length=160, null=True
                    ),
                ),
                (
                    "headline_uz",
                    models.CharField(
                        blank=True, help_text="Required to publish.", max_length=160, null=True
                    ),
                ),
                ("subheadline", models.CharField(blank=True, max_length=240)),
                ("subheadline_en", models.CharField(blank=True, max_length=240, null=True)),
                ("subheadline_ko", models.CharField(blank=True, max_length=240, null=True)),
                ("subheadline_uz", models.CharField(blank=True, max_length=240, null=True)),
                ("intro", models.TextField(blank=True, help_text="Markdown.")),
                ("intro_en", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("intro_ko", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("intro_uz", models.TextField(blank=True, help_text="Markdown.", null=True)),
                (
                    "hero_variant",
                    models.CharField(
                        choices=[
                            ("portrait", "Portrait"),
                            ("split", "Split"),
                            ("bilingual", "Bilingual"),
                            ("statement", "Statement (no photo)"),
                        ],
                        default="portrait",
                        max_length=10,
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        choices=[("default", "Default")], default="default", max_length=20
                    ),
                ),
                ("router_prompt", models.CharField(blank=True, max_length=120)),
                ("router_prompt_en", models.CharField(blank=True, max_length=120, null=True)),
                ("router_prompt_ko", models.CharField(blank=True, max_length=120, null=True)),
                ("router_prompt_uz", models.CharField(blank=True, max_length=120, null=True)),
                ("router_blurb", models.CharField(blank=True, max_length=240)),
                ("router_blurb_en", models.CharField(blank=True, max_length=240, null=True)),
                ("router_blurb_ko", models.CharField(blank=True, max_length=240, null=True)),
                ("router_blurb_uz", models.CharField(blank=True, max_length=240, null=True)),
                ("show_in_switcher", models.BooleanField(default=True)),
                ("show_in_router", models.BooleanField(default=True)),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=5),
                        default=apps.profiles.models.default_languages,
                        help_text="Languages this profile is published in. English is always included.",
                    ),
                ),
                (
                    "primary_cta",
                    models.CharField(
                        choices=[
                            ("contact", "Contact"),
                            ("resume", "Download CV"),
                            ("projects", "Projects"),
                        ],
                        default="contact",
                        max_length=10,
                    ),
                ),
                ("primary_cta_label", models.CharField(blank=True, max_length=60)),
                ("primary_cta_label_en", models.CharField(blank=True, max_length=60, null=True)),
                ("primary_cta_label_ko", models.CharField(blank=True, max_length=60, null=True)),
                ("primary_cta_label_uz", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "contact_form_variant",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("project_inquiry", "Project inquiry"),
                            ("language_request", "Language request"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty: the portrait in site settings.",
                        limit_choices_to={"kind": "image"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.mediaasset",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "image"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.mediaasset",
                        verbose_name="Open Graph image",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileContactChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="This profile's main channel. At most one per profile.",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_links",
                        to="career.contactchannel",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_links",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_links",
                        to="career.education",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_links",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile education",
                "verbose_name_plural": "profile education",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("summary_override", models.TextField(blank=True)),
                ("summary_override_en", models.TextField(blank=True, null=True)),
                ("summary_override_ko", models.TextField(blank=True, null=True)),
                ("summary_override_uz", models.TextField(blank=True, null=True)),
                ("highlights_override", models.TextField(blank=True, help_text="Markdown.")),
                (
                    "highlights_override_en",
                    models.TextField(blank=True, help_text="Markdown.", null=True),
                ),
                (
                    "highlights_override_ko",
                    models.TextField(blank=True, help_text="Markdown.", null=True),
                ),
                (
                    "highlights_override_uz",
                    models.TextField(blank=True, help_text="Markdown.", null=True),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_links",
                        to="career.experience",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_links",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="The project's primary profile: its back link when the referrer is unknown. At most one per project.",
                    ),
                ),
                ("summary_override", models.CharField(blank=True, max_length=300)),
                ("summary_override_en", models.CharField(blank=True, max_length=300, null=True)),
                ("summary_override_ko", models.CharField(blank=True, max_length=300, null=True)),
                ("summary_override_uz", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="profiles.profile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_links",
                        to="career.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("about", "About"),
                            ("custom_markdown", "Custom text"),
                            ("evidence_strip", "Evidence strip"),
                            ("skills", "Skills"),
                            ("projects", "Projects"),
                            ("experience", "Experience"),
                            ("education", "Education"),
                            ("services", "Services"),
                            ("language_pairs", "Language pairs"),
                            ("resume_cta", "Resume call to action"),
                            ("contact", "Contact"),
                            ("profile_router", "Profile router"),
                        ],
                        max_length=20,
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=120)),
                ("heading_en", models.CharField(blank=True, max_length=120, null=True)),
                ("heading_ko", models.CharField(blank=True, max_length=120, null=True)),
                ("heading_uz", models.CharField(blank=True, max_length=120, null=True)),
                ("intro", models.TextField(blank=True)),
                ("intro_en", models.TextField(blank=True, null=True)),
                ("intro_ko", models.TextField(blank=True, null=True)),
                ("intro_uz", models.TextField(blank=True, null=True)),
                (
                    "body",
                    models.TextField(blank=True, help_text="Markdown. Custom text sections only."),
                ),
                (
                    "body_en",
                    models.TextField(
                        blank=True, help_text="Markdown. Custom text sections only.", null=True
                    ),
                ),
                (
                    "body_ko",
                    models.TextField(
                        blank=True, help_text="Markdown. Custom text sections only.", null=True
                    ),
                ),
                (
                    "body_uz",
                    models.TextField(
                        blank=True, help_text="Markdown. Custom text sections only.", null=True
                    ),
                ),
                (
                    "layout_variant",
                    models.CharField(
                        choices=[("default", "Default")], default="default", max_length=20
                    ),
                ),
                (
                    "item_limit",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="List sections only: show at most this many items.",
                        null=True,
                    ),
                ),
                (
                    "anchor",
                    models.SlugField(blank=True, help_text="In-page link target.", max_length=60),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_links",
                        to="profiles.profile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_links",
                        to="career.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="Emphasised on this profile."),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_links",
                        to="profiles.profile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_links",
                        to="career.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug__regex", "^[a-z0-9]+(-[a-z0-9]+)*$")),
                name="profiles_profile_slug_format",
                violation_error_message="Use lowercase letters, digits and single hyphens only.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "home")),
                fields=("kind",),
                name="profiles_profile_one_home",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "about")),
                fields=("kind",),
                name="profiles_profile_one_about",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["home", "about"]),
                    models.Q(
                        (
                            "slug__in",
                            [
                                ".well-known",
                                "_styleguide",
                                "about",
                                "accounts",
                                "admin",
                                "api",
                                "blog",
                                "contact",
                                "dashboard",
                                "e",
                                "en",
                                "healthz",
                                "ko",
                                "map",
                                "media",
                                "privacy",
                                "projects",
                                "resume",
                                "robots.txt",
                                "sitemap.xml",
                                "skills",
                                "static",
                                "uz",
                            ],
                        ),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="profiles_profile_slug_not_reserved",
                violation_error_message="This slug is reserved for a site route or language.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("languages__contains", ["en"]), ("languages__contained_by", ["en", "ko", "uz"])
                ),
                name="profiles_profile_languages_valid",
                violation_error_message="Languages must include English and be site languages.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["home", "about", "role"])),
                name="profiles_profile_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hero_variant__in", ["portrait", "split", "bilingual", "statement"])
                ),
                name="profiles_profile_hero_variant_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(("accent__in", ["default"])),
                name="profiles_profile_accent_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(("primary_cta__in", ["contact", "resume", "projects"])),
                name="profiles_profile_primary_cta_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contact_form_variant__in", ["general", "project_inquiry", "language_request"])
                ),
                name="profiles_profile_contact_form_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(("name_en__isnull", False), ("name_en__regex", "\\S")),
                name="profiles_profile_name_en",
                violation_error_message="English is required.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    models.Q(("headline_en__isnull", False), ("headline_en__regex", "\\S")),
                    _connector="OR",
                ),
                name="profiles_profile_headline_to_publish",
                violation_error_message="This must be filled in before the record is published.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False), ("published_at__isnull", False), _connector="OR"
                ),
                name="profiles_profile_published_at_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    models.Q(
                        models.Q(("name__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("name_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("name_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("name_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("switcher_label__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("switcher_label_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("switcher_label_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("switcher_label_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("headline__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("headline_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("headline_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("headline_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("subheadline__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("subheadline_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("subheadline_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("subheadline_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("intro__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("intro_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("intro_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("intro_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("router_prompt__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("router_prompt_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("router_prompt_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("router_prompt_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("router_blurb__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("router_blurb_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("router_blurb_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("router_blurb_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("primary_cta_label__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(
                            ("primary_cta_label_en__icontains", "TODO(odilbek"), _negated=True
                        ),
                        models.Q(
                            ("primary_cta_label_ko__icontains", "TODO(odilbek"), _negated=True
                        ),
                        models.Q(
                            ("primary_cta_label_uz__icontains", "TODO(odilbek"), _negated=True
                        ),
                        models.Q(("seo_title__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_title_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_title_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_title_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_description__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_description_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_description_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_description_uz__icontains", "TODO(odilbek"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="profiles_profile_no_todo_when_published",
                violation_error_message="Resolve every TODO(odilbek) before publishing.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilecontactchannel",
            constraint=models.UniqueConstraint(
                fields=("profile", "channel"), name="profiles_profilechannel_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilecontactchannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("profile",),
                name="profiles_profilechannel_one_primary",
                violation_error_message="This profile already has a primary channel.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profileeducation",
            constraint=models.UniqueConstraint(
                fields=("profile", "education"), name="profiles_profileeducation_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="profileexperience",
            constraint=models.UniqueConstraint(
                fields=("profile", "experience"), name="profiles_profileexperience_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="profileproject",
            constraint=models.UniqueConstraint(
                fields=("profile", "project"), name="profiles_profileproject_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="profileproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("project",),
                name="profiles_profileproject_one_primary",
                violation_error_message="This project already has a primary profile.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "section_type__in",
                        [
                            "about",
                            "custom_markdown",
                            "evidence_strip",
                            "skills",
                            "projects",
                            "experience",
                            "education",
                            "services",
                            "language_pairs",
                            "resume_cta",
                            "contact",
                            "profile_router",
                        ],
                    )
                ),
                name="profiles_profilesection_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("layout_variant__in", ["default"]), ("section_type", "about")),
                    models.Q(
                        ("layout_variant__in", ["default"]), ("section_type", "custom_markdown")
                    ),
                    models.Q(
                        ("layout_variant__in", ["default"]), ("section_type", "evidence_strip")
                    ),
                    models.Q(("layout_variant__in", ["default"]), ("section_type", "skills")),
                    models.Q(("layout_variant__in", ["default"]), ("section_type", "projects")),
                    models.Q(("layout_variant__in", ["default"]), ("section_type", "experience")),
                    models.Q(("layout_variant__in", ["default"]), ("section_type", "education")),
                    models.Q(("layout_variant__in", ["default"]), ("section_type", "services")),
                    models.Q(
                        ("layout_variant__in", ["default"]), ("section_type", "language_pairs")
                    ),
                    models.Q(("layout_variant__in", ["default"]), ("section_type", "resume_cta")),
                    models.Q(("layout_variant__in", ["default"]), ("section_type", "contact")),
                    models.Q(
                        ("layout_variant__in", ["default"]), ("section_type", "profile_router")
                    ),
                    _connector="OR",
                ),
                name="profiles_profilesection_layout_valid",
                violation_error_message="This layout is not available for this section type.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section_type", "custom_markdown"), _negated=True),
                fields=("profile", "section_type"),
                name="profiles_profilesection_one_per_type",
                violation_error_message="This profile already has a section of this type.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("section_type", "custom_markdown"),
                    models.Q(
                        models.Q(("body__isnull", True), ("body", ""), _connector="OR"),
                        models.Q(("body_en__isnull", True), ("body_en", ""), _connector="OR"),
                        models.Q(("body_ko__isnull", True), ("body_ko", ""), _connector="OR"),
                        models.Q(("body_uz__isnull", True), ("body_uz", ""), _connector="OR"),
                    ),
                    _connector="OR",
                ),
                name="profiles_profilesection_body_custom_only",
                violation_error_message="Only custom text sections have a body.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("item_limit__isnull", True),
                    models.Q(
                        ("item_limit__gte", 1),
                        (
                            "section_type__in",
                            [
                                "education",
                                "experience",
                                "language_pairs",
                                "projects",
                                "services",
                                "skills",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="profiles_profilesection_item_limit_valid",
                violation_error_message="Only list sections can limit items, and to at least 1.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("anchor", ""), ("anchor__regex", "^[a-z0-9]+(-[a-z0-9]+)*$"), _connector="OR"
                ),
                name="profiles_profilesection_anchor_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("anchor", ""), _negated=True),
                fields=("profile", "anchor"),
                name="profiles_profilesection_anchor_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_enabled", False),
                    models.Q(
                        models.Q(("heading__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("heading_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("heading_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("heading_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("intro__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("intro_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("intro_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("intro_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("body__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("body_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("body_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("body_uz__icontains", "TODO(odilbek"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="profiles_profilesection_no_todo_when_enabled",
                violation_error_message="Resolve every TODO(odilbek) before enabling a section.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profileservice",
            constraint=models.UniqueConstraint(
                fields=("profile", "service"), name="profiles_profileservice_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="profileskill",
            constraint=models.UniqueConstraint(
                fields=("profile", "skill"), name="profiles_profileskill_pair"
            ),
        ),
    ]
