# Generated by Django 6.1.1 on 2026-09-27 04:40

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_label", models.CharField(max_length=60)),
                ("key", models.CharField(max_length=120)),
                ("object_id", models.PositiveBigIntegerField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["model_label", "key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model_label", "key"), name="core_importedrecord_unique_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(editable=False, max_length=255, upload_to="")),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("pdf", "PDF")], editable=False, max_length=5
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=250)),
                ("alt_text_en", models.CharField(blank=True, max_length=250, null=True)),
                ("alt_text_ko", models.CharField(blank=True, max_length=250, null=True)),
                ("alt_text_uz", models.CharField(blank=True, max_length=250, null=True)),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("caption_en", models.CharField(blank=True, max_length=300, null=True)),
                ("caption_ko", models.CharField(blank=True, max_length=300, null=True)),
                ("caption_uz", models.CharField(blank=True, max_length=300, null=True)),
                ("width", models.PositiveIntegerField(editable=False, null=True)),
                ("height", models.PositiveIntegerField(editable=False, null=True)),
                ("bytes", models.PositiveBigIntegerField(editable=False)),
                ("sha256", models.CharField(editable=False, max_length=64, unique=True)),
                ("focal_x", models.FloatField(default=0.5)),
                ("focal_y", models.FloatField(default=0.5)),
                ("variants", models.JSONField(blank=True, default=dict, editable=False)),
            ],
            options={
                "verbose_name": "media asset",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["image", "pdf"])),
                        name="core_mediaasset_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sha256__regex", "^[0-9a-f]{64}$")),
                        name="core_mediaasset_sha256_hex",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("bytes__gte", 1)), name="core_mediaasset_bytes_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("height__gte", 1),
                                ("height__isnull", False),
                                ("kind", "image"),
                                ("width__gte", 1),
                                ("width__isnull", False),
                            ),
                            models.Q(
                                ("height__isnull", True), ("kind", "pdf"), ("width__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="core_mediaasset_dimensions_match_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind", "pdf"),
                            models.Q(("alt_text_en__isnull", False), ("alt_text_en__regex", "\\S")),
                            _connector="OR",
                        ),
                        name="core_mediaasset_image_alt_text_en",
                        violation_error_message="Images need English alt text.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("focal_x__gte", 0),
                            ("focal_x__lte", 1),
                            ("focal_y__gte", 0),
                            ("focal_y__lte", 1),
                        ),
                        name="core_mediaasset_focal_point_in_range",
                        violation_error_message="The focal point must be between 0 and 1.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=120)),
                ("owner_name_en", models.CharField(blank=True, max_length=120, null=True)),
                ("owner_name_ko", models.CharField(blank=True, max_length=120, null=True)),
                ("owner_name_uz", models.CharField(blank=True, max_length=120, null=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("tagline_en", models.CharField(blank=True, max_length=200, null=True)),
                ("tagline_ko", models.CharField(blank=True, max_length=200, null=True)),
                ("tagline_uz", models.CharField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("location_en", models.CharField(blank=True, max_length=120, null=True)),
                ("location_ko", models.CharField(blank=True, max_length=120, null=True)),
                ("location_uz", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        max_length=64,
                        validators=[apps.core.models.validate_timezone],
                    ),
                ),
                ("public_email", models.EmailField(blank=True, max_length=254)),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("limited", "Limited availability"),
                            ("unavailable", "Not available"),
                        ],
                        max_length=12,
                    ),
                ),
                ("availability_note", models.CharField(blank=True, max_length=200)),
                ("availability_note_en", models.CharField(blank=True, max_length=200, null=True)),
                ("availability_note_ko", models.CharField(blank=True, max_length=200, null=True)),
                ("availability_note_uz", models.CharField(blank=True, max_length=200, null=True)),
                ("response_time_note", models.CharField(blank=True, max_length=200)),
                ("response_time_note_en", models.CharField(blank=True, max_length=200, null=True)),
                ("response_time_note_ko", models.CharField(blank=True, max_length=200, null=True)),
                ("response_time_note_uz", models.CharField(blank=True, max_length=200, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_title_en", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_title_ko", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_title_uz", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("seo_description_en", models.CharField(blank=True, max_length=160, null=True)),
                ("seo_description_ko", models.CharField(blank=True, max_length=160, null=True)),
                ("seo_description_uz", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "default_og_image",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "image"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.mediaasset",
                        verbose_name="default Open Graph image",
                    ),
                ),
                (
                    "portrait",
                    models.ForeignKey(
                        blank=True,
                        help_text="The default hero and About photo.",
                        limit_choices_to={"kind": "image"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="core_sitesettings_singleton"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("availability__in", ["available", "limited", "unavailable", ""])
                        ),
                        name="core_sitesettings_availability_valid",
                    ),
                ],
            },
        ),
    ]
