# Generated by Django 6.1.1 on 2026-09-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedrecord",
            name="origin",
            field=models.CharField(
                choices=[
                    ("draft", "draft_content (real content)"),
                    ("demo", "seed_demo (fictional demo content)"),
                ],
                default="draft",
                max_length=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="importedrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin__in", ["draft", "demo"])),
                name="core_importedrecord_origin_valid",
            ),
        ),
    ]
