# Generated by Django 6.1.1 on 2026-09-27 04:40

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False, editable=False)),
                ("published_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80, null=True)),
                ("name_ko", models.CharField(max_length=80, null=True)),
                ("name_uz", models.CharField(max_length=80, null=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ko", models.TextField(blank=True, null=True)),
                ("description_uz", models.TextField(blank=True, null=True)),
                (
                    "level_label",
                    models.CharField(
                        blank=True,
                        help_text="As Odilbek states it, e.g. 'Native' or 'TOPIK Level 6'. Never inferred.",
                        max_length=80,
                    ),
                ),
                (
                    "level_label_en",
                    models.CharField(
                        blank=True,
                        help_text="As Odilbek states it, e.g. 'Native' or 'TOPIK Level 6'. Never inferred.",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "level_label_ko",
                    models.CharField(
                        blank=True,
                        help_text="As Odilbek states it, e.g. 'Native' or 'TOPIK Level 6'. Never inferred.",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "level_label_uz",
                    models.CharField(
                        blank=True,
                        help_text="As Odilbek states it, e.g. 'Native' or 'TOPIK Level 6'. Never inferred.",
                        max_length=80,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False, editable=False)),
                ("published_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("linkedin", "LinkedIn"),
                            ("upwork", "Upwork"),
                            ("github", "GitHub"),
                            ("kakaotalk", "KakaoTalk"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("label_en", models.CharField(max_length=80, null=True)),
                ("label_ko", models.CharField(max_length=80, null=True)),
                ("label_uz", models.CharField(max_length=80, null=True)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[django.core.validators.URLValidator(schemes=("http", "https"))],
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        blank=True,
                        help_text="E.g. an email address or @username. Email links are built from this.",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                [
                                    "email",
                                    "telegram",
                                    "whatsapp",
                                    "linkedin",
                                    "upwork",
                                    "github",
                                    "kakaotalk",
                                    "other",
                                ],
                            )
                        ),
                        name="career_contactchannel_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("label_en__isnull", False), ("label_en__regex", "\\S")),
                        name="career_contactchannel_label_en",
                        violation_error_message="English is required.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("url", ""), ("url__regex", "^https?://"), _connector="OR"
                        ),
                        name="career_contactchannel_url_http",
                        violation_error_message="Only http:// and https:// links are allowed.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("url", ""), _negated=True),
                            models.Q(("handle", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="career_contactchannel_has_target",
                        violation_error_message="Give a URL or a handle.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_published", False),
                            ("published_at__isnull", False),
                            _connector="OR",
                        ),
                        name="career_contactchannel_published_at_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_published", False),
                            models.Q(
                                models.Q(("handle__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("label__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("label_en__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("label_ko__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("label_uz__icontains", "TODO(odilbek"), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="career_contactchannel_no_todo_when_published",
                        violation_error_message="Resolve every TODO(odilbek) before publishing.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False, editable=False)),
                ("published_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_title_en", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_title_ko", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_title_uz", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("seo_description_en", models.CharField(blank=True, max_length=160, null=True)),
                ("seo_description_ko", models.CharField(blank=True, max_length=160, null=True)),
                ("seo_description_uz", models.CharField(blank=True, max_length=160, null=True)),
                ("title", models.CharField(max_length=120)),
                ("title_en", models.CharField(max_length=120, null=True)),
                ("title_ko", models.CharField(max_length=120, null=True)),
                ("title_uz", models.CharField(max_length=120, null=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "summary",
                    models.CharField(blank=True, help_text="Required to publish.", max_length=300),
                ),
                (
                    "summary_en",
                    models.CharField(
                        blank=True, help_text="Required to publish.", max_length=300, null=True
                    ),
                ),
                (
                    "summary_ko",
                    models.CharField(
                        blank=True, help_text="Required to publish.", max_length=300, null=True
                    ),
                ),
                (
                    "summary_uz",
                    models.CharField(
                        blank=True, help_text="Required to publish.", max_length=300, null=True
                    ),
                ),
                ("context", models.TextField(blank=True)),
                ("context_en", models.TextField(blank=True, null=True)),
                ("context_ko", models.TextField(blank=True, null=True)),
                ("context_uz", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, help_text="Markdown.")),
                ("description_en", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("description_ko", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("description_uz", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("highlights", models.TextField(blank=True, help_text="Markdown.")),
                ("highlights_en", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("highlights_ko", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("highlights_uz", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("role_en", models.CharField(blank=True, max_length=120, null=True)),
                ("role_ko", models.CharField(blank=True, max_length=120, null=True)),
                ("role_uz", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "project_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("live", "Live"),
                            ("in_progress", "In progress"),
                            ("archived", "Archived"),
                            ("concept", "Concept"),
                        ],
                        max_length=12,
                    ),
                ),
                ("started_on", models.DateField(blank=True, null=True)),
                ("ended_on", models.DateField(blank=True, null=True)),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[django.core.validators.URLValidator(schemes=("http", "https"))],
                    ),
                ),
                (
                    "demo_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[django.core.validators.URLValidator(schemes=("http", "https"))],
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "is_listed",
                    models.BooleanField(
                        default=True,
                        help_text="Unlisted projects are reachable only at their own URL: never listed, never indexed, never in the sitemap.",
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "image"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.mediaasset",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "image"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.mediaasset",
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(blank=True, related_name="projects", to="career.skill"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LanguagePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "modes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("document", "Document translation"),
                                ("consecutive", "Consecutive interpreting"),
                                ("simultaneous", "Simultaneous interpreting"),
                                ("localization", "Localization"),
                                ("review", "Review and proofreading"),
                            ],
                            max_length=12,
                        )
                    ),
                ),
                ("domains", models.CharField(blank=True, max_length=200)),
                ("domains_en", models.CharField(blank=True, max_length=200, null=True)),
                ("domains_ko", models.CharField(blank=True, max_length=200, null=True)),
                ("domains_uz", models.CharField(blank=True, max_length=200, null=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("note_en", models.CharField(blank=True, max_length=300, null=True)),
                ("note_ko", models.CharField(blank=True, max_length=300, null=True)),
                ("note_uz", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        limit_choices_to={"category__kind": "language"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pairs_from",
                        to="career.skill",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        limit_choices_to={"category__kind": "language"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pairs_to",
                        to="career.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False, editable=False)),
                ("published_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("role", models.CharField(max_length=120)),
                ("role_en", models.CharField(max_length=120, null=True)),
                ("role_ko", models.CharField(max_length=120, null=True)),
                ("role_uz", models.CharField(max_length=120, null=True)),
                ("organization", models.CharField(max_length=160)),
                ("organization_en", models.CharField(max_length=160, null=True)),
                ("organization_ko", models.CharField(max_length=160, null=True)),
                ("organization_uz", models.CharField(max_length=160, null=True)),
                (
                    "organization_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[django.core.validators.URLValidator(schemes=("http", "https"))],
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("location_en", models.CharField(blank=True, max_length=120, null=True)),
                ("location_ko", models.CharField(blank=True, max_length=120, null=True)),
                ("location_uz", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full-time"),
                            ("freelance", "Freelance"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("volunteer", "Volunteer"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "started_on",
                    models.DateField(blank=True, help_text="Required to publish.", null=True),
                ),
                (
                    "ended_on",
                    models.DateField(
                        blank=True, help_text="Empty means the role is current.", null=True
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("summary_en", models.TextField(blank=True, null=True)),
                ("summary_ko", models.TextField(blank=True, null=True)),
                ("summary_uz", models.TextField(blank=True, null=True)),
                ("highlights", models.TextField(blank=True, help_text="Markdown.")),
                ("highlights_en", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("highlights_ko", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("highlights_uz", models.TextField(blank=True, help_text="Markdown.", null=True)),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, related_name="experiences", to="career.project"
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="experiences", to="career.skill"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "experience",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False, editable=False)),
                ("published_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("institution", models.CharField(max_length=160)),
                ("institution_en", models.CharField(max_length=160, null=True)),
                ("institution_ko", models.CharField(max_length=160, null=True)),
                ("institution_uz", models.CharField(max_length=160, null=True)),
                ("credential", models.CharField(blank=True, max_length=160)),
                ("credential_en", models.CharField(blank=True, max_length=160, null=True)),
                ("credential_ko", models.CharField(blank=True, max_length=160, null=True)),
                ("credential_uz", models.CharField(blank=True, max_length=160, null=True)),
                ("field", models.CharField(blank=True, max_length=160)),
                ("field_en", models.CharField(blank=True, max_length=160, null=True)),
                ("field_ko", models.CharField(blank=True, max_length=160, null=True)),
                ("field_uz", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("degree", "Degree"),
                            ("course", "Course"),
                            ("certification", "Certification"),
                            ("language_test", "Language test"),
                        ],
                        max_length=15,
                    ),
                ),
                ("started_on", models.DateField(blank=True, null=True)),
                ("ended_on", models.DateField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        help_text="As stated on the credential, e.g. 'TOPIK Level 6'.",
                        max_length=80,
                    ),
                ),
                (
                    "result_en",
                    models.CharField(
                        blank=True,
                        help_text="As stated on the credential, e.g. 'TOPIK Level 6'.",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "result_ko",
                    models.CharField(
                        blank=True,
                        help_text="As stated on the credential, e.g. 'TOPIK Level 6'.",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "result_uz",
                    models.CharField(
                        blank=True,
                        help_text="As stated on the credential, e.g. 'TOPIK Level 6'.",
                        max_length=80,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ko", models.TextField(blank=True, null=True)),
                ("description_uz", models.TextField(blank=True, null=True)),
                (
                    "credential_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        validators=[django.core.validators.URLValidator(schemes=("http", "https"))],
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(blank=True, related_name="education", to="career.skill"),
                ),
            ],
            options={
                "verbose_name_plural": "education",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("name", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80, null=True)),
                ("name_ko", models.CharField(max_length=80, null=True)),
                ("name_uz", models.CharField(max_length=80, null=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("language", "Spoken language"),
                            ("domain", "Domain"),
                            ("tool", "Tool"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "skill categories",
                "ordering": ["order", "id"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("slug__regex", "^[a-z0-9]+(-[a-z0-9]+)*$")),
                        name="career_skillcategory_slug_format",
                        violation_error_message="Use lowercase letters, digits and single hyphens only.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["technical", "language", "domain", "tool"])
                        ),
                        name="career_skillcategory_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name_en__isnull", False), ("name_en__regex", "\\S")),
                        name="career_skillcategory_name_en",
                        violation_error_message="English is required.",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="skills",
                to="career.skillcategory",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("caption_en", models.CharField(blank=True, max_length=300, null=True)),
                ("caption_ko", models.CharField(blank=True, max_length=300, null=True)),
                ("caption_uz", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        limit_choices_to={"kind": "image"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.mediaasset",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="career.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project media",
                "verbose_name_plural": "project media",
                "ordering": ["order", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "asset"), name="career_projectmedia_unique_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False, editable=False)),
                ("published_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("title", models.CharField(max_length=120)),
                ("title_en", models.CharField(max_length=120, null=True)),
                ("title_ko", models.CharField(max_length=120, null=True)),
                ("title_uz", models.CharField(max_length=120, null=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("summary_en", models.CharField(blank=True, max_length=300, null=True)),
                ("summary_ko", models.CharField(blank=True, max_length=300, null=True)),
                ("summary_uz", models.CharField(blank=True, max_length=300, null=True)),
                ("description", models.TextField(blank=True, help_text="Markdown.")),
                ("description_en", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("description_ko", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("description_uz", models.TextField(blank=True, help_text="Markdown.", null=True)),
                ("pricing_note", models.CharField(blank=True, max_length=200)),
                ("pricing_note_en", models.CharField(blank=True, max_length=200, null=True)),
                ("pricing_note_ko", models.CharField(blank=True, max_length=200, null=True)),
                ("pricing_note_uz", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "skills",
                    models.ManyToManyField(blank=True, related_name="services", to="career.skill"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("slug__regex", "^[a-z0-9]+(-[a-z0-9]+)*$")),
                        name="career_service_slug_format",
                        violation_error_message="Use lowercase letters, digits and single hyphens only.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("title_en__isnull", False), ("title_en__regex", "\\S")),
                        name="career_service_title_en",
                        violation_error_message="English is required.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_published", False),
                            ("published_at__isnull", False),
                            _connector="OR",
                        ),
                        name="career_service_published_at_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_published", False),
                            models.Q(
                                models.Q(("title__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("title_en__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("title_ko__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("title_uz__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("summary__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("summary_en__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("summary_ko__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("summary_uz__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(("description__icontains", "TODO(odilbek"), _negated=True),
                                models.Q(
                                    ("description_en__icontains", "TODO(odilbek"), _negated=True
                                ),
                                models.Q(
                                    ("description_ko__icontains", "TODO(odilbek"), _negated=True
                                ),
                                models.Q(
                                    ("description_uz__icontains", "TODO(odilbek"), _negated=True
                                ),
                                models.Q(
                                    ("pricing_note__icontains", "TODO(odilbek"), _negated=True
                                ),
                                models.Q(
                                    ("pricing_note_en__icontains", "TODO(odilbek"), _negated=True
                                ),
                                models.Q(
                                    ("pricing_note_ko__icontains", "TODO(odilbek"), _negated=True
                                ),
                                models.Q(
                                    ("pricing_note_uz__icontains", "TODO(odilbek"), _negated=True
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="career_service_no_todo_when_published",
                        violation_error_message="Resolve every TODO(odilbek) before publishing.",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug__regex", "^[a-z0-9]+(-[a-z0-9]+)*$")),
                name="career_project_slug_format",
                violation_error_message="Use lowercase letters, digits and single hyphens only.",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("title_en__isnull", False), ("title_en__regex", "\\S")),
                name="career_project_title_en",
                violation_error_message="English is required.",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    models.Q(("summary_en__isnull", False), ("summary_en__regex", "\\S")),
                    _connector="OR",
                ),
                name="career_project_summary_to_publish",
                violation_error_message="This must be filled in before the record is published.",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("github_url", ""), ("github_url__regex", "^https?://"), _connector="OR"
                ),
                name="career_project_github_url_http",
                violation_error_message="Only http:// and https:// links are allowed.",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("demo_url", ""), ("demo_url__regex", "^https?://"), _connector="OR"
                ),
                name="career_project_demo_url_http",
                violation_error_message="Only http:// and https:// links are allowed.",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("started_on__isnull", True),
                    ("ended_on__isnull", True),
                    ("ended_on__gte", models.F("started_on")),
                    _connector="OR",
                ),
                name="career_project_dates_in_order",
                violation_error_message="The end date cannot be before the start date.",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("project_status__in", ["live", "in_progress", "archived", "concept", ""])
                ),
                name="career_project_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False), ("published_at__isnull", False), _connector="OR"
                ),
                name="career_project_published_at_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    models.Q(
                        models.Q(("title__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("title_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("title_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("title_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("summary__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("summary_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("summary_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("summary_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("context__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("context_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("context_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("context_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("highlights__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("highlights_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("highlights_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("highlights_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("role__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("role_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("role_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("role_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_title__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_title_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_title_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_title_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_description__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_description_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_description_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("seo_description_uz__icontains", "TODO(odilbek"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="career_project_no_todo_when_published",
                violation_error_message="Resolve every TODO(odilbek) before publishing.",
            ),
        ),
        migrations.AddConstraint(
            model_name="languagepair",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="career_languagepair_distinct",
                violation_error_message="A language pair needs two different languages.",
            ),
        ),
        migrations.AddConstraint(
            model_name="languagepair",
            constraint=models.UniqueConstraint(
                fields=("source", "target"), name="career_languagepair_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="languagepair",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("modes__len__gte", 1),
                    (
                        "modes__contained_by",
                        ["document", "consecutive", "simultaneous", "localization", "review"],
                    ),
                ),
                name="career_languagepair_modes_valid",
                violation_error_message="Choose at least one valid mode.",
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role_en__isnull", False),
                    ("role_en__regex", "\\S"),
                    ("organization_en__isnull", False),
                    ("organization_en__regex", "\\S"),
                ),
                name="career_experience_role_org_en",
                violation_error_message="English is required.",
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("organization_url", ""),
                    ("organization_url__regex", "^https?://"),
                    _connector="OR",
                ),
                name="career_experience_org_url_http",
                violation_error_message="Only http:// and https:// links are allowed.",
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("started_on__isnull", True),
                    ("ended_on__isnull", True),
                    ("ended_on__gte", models.F("started_on")),
                    _connector="OR",
                ),
                name="career_experience_dates_in_order",
                violation_error_message="The end date cannot be before the start date.",
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "employment_type__in",
                        ["full_time", "freelance", "contract", "internship", "volunteer", ""],
                    )
                ),
                name="career_experience_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False), ("started_on__isnull", False), _connector="OR"
                ),
                name="career_experience_start_to_publish",
                violation_error_message="This must be filled in before the record is published.",
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False), ("published_at__isnull", False), _connector="OR"
                ),
                name="career_experience_published_at_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    models.Q(
                        models.Q(("role__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("role_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("role_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("role_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("organization__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("organization_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("organization_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("organization_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("location__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("location_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("location_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("location_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("summary__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("summary_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("summary_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("summary_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("highlights__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("highlights_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("highlights_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("highlights_uz__icontains", "TODO(odilbek"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="career_experience_no_todo_when_published",
                violation_error_message="Resolve every TODO(odilbek) before publishing.",
            ),
        ),
        migrations.AddConstraint(
            model_name="education",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("institution_en__isnull", False), ("institution_en__regex", "\\S")
                ),
                name="career_education_institution_en",
                violation_error_message="English is required.",
            ),
        ),
        migrations.AddConstraint(
            model_name="education",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("credential_url", ""), ("credential_url__regex", "^https?://"), _connector="OR"
                ),
                name="career_education_credential_url_http",
                violation_error_message="Only http:// and https:// links are allowed.",
            ),
        ),
        migrations.AddConstraint(
            model_name="education",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("started_on__isnull", True),
                    ("ended_on__isnull", True),
                    ("ended_on__gte", models.F("started_on")),
                    _connector="OR",
                ),
                name="career_education_dates_in_order",
                violation_error_message="The end date cannot be before the start date.",
            ),
        ),
        migrations.AddConstraint(
            model_name="education",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["degree", "course", "certification", "language_test", ""])
                ),
                name="career_education_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="education",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False), ("published_at__isnull", False), _connector="OR"
                ),
                name="career_education_published_at_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="education",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    models.Q(
                        models.Q(("institution__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("institution_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("institution_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("institution_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("credential__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("credential_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("credential_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("credential_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("field__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("field_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("field_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("field_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("result__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("result_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("result_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("result_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description_uz__icontains", "TODO(odilbek"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="career_education_no_todo_when_published",
                violation_error_message="Resolve every TODO(odilbek) before publishing.",
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug__regex", "^[a-z0-9]+(-[a-z0-9]+)*$")),
                name="career_skill_slug_format",
                violation_error_message="Use lowercase letters, digits and single hyphens only.",
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.CheckConstraint(
                condition=models.Q(("name_en__isnull", False), ("name_en__regex", "\\S")),
                name="career_skill_name_en",
                violation_error_message="English is required.",
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False), ("published_at__isnull", False), _connector="OR"
                ),
                name="career_skill_published_at_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False),
                    models.Q(
                        models.Q(("name__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("name_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("name_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("name_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("description_uz__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("level_label__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("level_label_en__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("level_label_ko__icontains", "TODO(odilbek"), _negated=True),
                        models.Q(("level_label_uz__icontains", "TODO(odilbek"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="career_skill_no_todo_when_published",
                violation_error_message="Resolve every TODO(odilbek) before publishing.",
            ),
        ),
    ]
